/**
 * Program Name: FraudAlert.java
 * Purpose: This class represents a fraud alert generated by the fraud detection engine.
 * @author Ainash Zhumagulova 
 * Date Jun 26, 2026
 */
package com.railway.models;

/**
 * 
 */
public record FraudAlert(
		int alertId,
    int passengerId,
    String fraudType,
    String alertDescription,
    String severity,
    String alertTime,
    boolean isReviewed
		)
{




  @Override
  public String toString() {
      return "FraudAlert[id=%d, passenger=%d, type=%s, severity=%s, reviewed=%b]"
          .formatted(alertId, passengerId, fraudType, severity, isReviewed);
  }
}
